import "../styles/globals.css";
import type { Metadata } from "next";
import { IBM_Plex_Mono, IBM_Plex_Sans } from "next/font/google";
import { Header } from "@/components/ui/Header/Header";
import { MLBProvider } from "../components/ui/MLBProvider";

const fontMono = IBM_Plex_Mono({
  variable: "--font-mono",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

const fontSans = IBM_Plex_Sans({
  variable: "--font-sans",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MLB App",
  description: "Generated by MLB app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontMono.variable} ${fontSans.variable}`}>
        <MLBProvider>
          <Header />
          {children}
        </MLBProvider>
      </body>
    </html>
  );
}
